# SPDX-FileCopyrightText: 2026 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

listenAddr: ":8080"
baseUrl: "http://localhost:8080"

subtypesFile: "subtypes.yaml"

providers:
  - name: "province-bz"
    eventsUrl: "https://content.api.opendatahub.testingmachine.eu/v1/Announcement?pagesize=200000&tagfilter=announcement%3Atraffic-event&removenullvalues=true&getasidarray=false&source=PROVINCE_BZ&fields=Id%2CTagIds%2CGeo%2CMapping%2C_Meta%2CStartTime%2CEndTime%2CFirstImport%2CLastChange%2CDetail"
    source: "PROVINCE_BZ"
    pollIntervalSeconds: 20
    idPrefix: "urn:announcements:provincebz:"
    internalSupplier: "ITPBZ"
    recipients:
      - type: "situation-publication"
        supplier: "IT492"
        description: "A22 - Brenner motorway"
        path: "/datex/2/province-bz/situation-publication.xml"
        enabled: true
